### PR TITLE
Use github actions to run tests on every PR

### PR DESCRIPTION
**Pull request by tzulberti-jampp**
* [x] Updated [CHANGELOG file](https://github.com/jampp/klaussfreire/blob/master/CHANGELOG.rst)
* [x] Added link at the end of [CHANGELOG file](https://github.com/jampp/klaussfreire/blob/master/CHANGELOG.rst)
* [x] Created test for the code changes
* [x] If required, updated the requirements.txt file

### CODE REVIEW

**Review by klaussfreire — COMMENTED** [review]
No pytest.ini?

**Comment by tzulberti-jampp** [comment]
> No pytest.ini?

Why should I add that script what should I add to it?

**Comment by klaussfreire** [comment]
> > No pytest.ini?
> 
> Why should I add that script what should I add to it?

Because otherwise it will find no tests:

```
============================================================================================================================= test session starts =============================================================================================================================
platform linux2 -- Python 2.7.14, pytest-4.6.9, py-1.8.1, pluggy-0.13.1
rootdir: /home/claudiofreire/src/clru, inifile: setup.cfg
plugins: forked-1.1.3, xdist-1.31.0, cov-2.8.1
collected 0 items / 2 errors                                                                                                                                                                                                                                                  

=================================================================================================================================== ERRORS ====================================================================================================================================
________________________________________________________________________________________________________________ ERROR collecting tests/test_pycuckoocache.py _________________________________________________________________________________________________________________
ImportError while importing test module '/home/claudiofreire/src/clru/tests/test_pycuckoocache.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/test_pycuckoocache.py:8: in <module>
    from clru.cuckoocache import pycuckoocache
E   ImportError: No module named clru.cuckoocache
__________________________________________________________________________________________________________________ ERROR collecting tests/test_pylrucache.py __________________________________________________________________________________________________________________
ImportError while importing test module '/home/claudiofreire/src/clru/tests/test_pylrucache.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/test_pylrucache.py:6: in <module>
    from clru.lrucache import pylrucache
E   ImportError: No module named clru.lrucache
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 2 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
=========================================================================================================================== 2 error in 0.09 seconds ===========================================================================================================================
```

**Comment by tzulberti-jampp** [comment]
> > > No pytest.ini?
> > 
> > 
> > Why should I add that script what should I add to it?
> 
> Because otherwise it will find no tests:
> 
> ```
> ============================================================================================================================= test session starts =============================================================================================================================
> platform linux2 -- Python 2.7.14, pytest-4.6.9, py-1.8.1, pluggy-0.13.1
> rootdir: /home/claudiofreire/src/clru, inifile: setup.cfg
> plugins: forked-1.1.3, xdist-1.31.0, cov-2.8.1
> collected 0 items / 2 errors                                                                                                                                                                                                                                                  
> 
> =================================================================================================================================== ERRORS ====================================================================================================================================
> ________________________________________________________________________________________________________________ ERROR collecting tests/test_pycuckoocache.py _________________________________________________________________________________________________________________
> ImportError while importing test module '/home/claudiofreire/src/clru/tests/test_pycuckoocache.py'.
> Hint: make sure your test modules/packages have valid Python names.
> Traceback:
> tests/test_pycuckoocache.py:8: in <module>
>     from clru.cuckoocache import pycuckoocache
> E   ImportError: No module named clru.cuckoocache
> __________________________________________________________________________________________________________________ ERROR collecting tests/test_pylrucache.py __________________________________________________________________________________________________________________
> ImportError while importing test module '/home/claudiofreire/src/clru/tests/test_pylrucache.py'.
> Hint: make sure your test modules/packages have valid Python names.
> Traceback:
> tests/test_pylrucache.py:6: in <module>
>     from clru.lrucache import pylrucache
> E   ImportError: No module named clru.lrucache
> !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 2 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
> =========================================================================================================================== 2 error in 0.09 seconds ===========================================================================================================================
> ```

You need to run `pip install -e . ` to be able to run the tests

**Comment by klaussfreire** [comment]
Tests must be runnable before installing the module. It's doable with a bit of config.

**Comment by klaussfreire** [comment]
Correction: actually, you just need to turn `tests` into an actual package (add `__init__.py`)

Then instead of pip install you can `python setup.py build_ext --inplace` which doesn't require writing into the virtualenv. Which is good.

**Review by klaussfreire — APPROVED** [review]

**Pull request merged**
